import Config

Code.require_file("rand.ex", "lib/hitbit/utils")

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :hitbit, HitbitWeb.Endpoint,
  secret_key_base: Hitbit.Utils.Rand.string(),
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

config :hitbit, Hitbit.Plug.CORS,
  origins: "*",
  methods: ["POST"]

# Expose graphiql route in development
config :hitbit, HitbitWeb.Router, graphiql: true

# Database configuration
config :hitbit, Hitbit.Repo,
  database: System.get_env("DB_NAME", "postgres"),
  username: System.get_env("DB_USER", "postgres"),
  password: System.get_env("DB_PASS", "postgres"),
  hostname: System.get_env("DB_HOST", "localhost"),
  port: System.get_env("DB_PORT", "5432"),
  pool_size: 15

# Guardian configuration
config :hitbit, Hitbit.Guardian, secret_key: Hitbit.Utils.Rand.string()

# Session controller configuration
config :hitbit, HitbitWeb.SessionController, frontend_origin: "http://localhost"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :hitbit, HitbitWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/hitbit_web/views/.*(ex)$},
      ~r{lib/hitbit_web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 30

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
